/* error codes  */
#define INSUFFICIENT_NUMBER_OF_PARAMETERS		1
#define INVALID_INPUT_CHARACTER				2
#define INVALID_INDEX					3
#define NON_NUMERIC_CHARACTER				4
#define IMPOSSIBLE_PLUGBOARD_CONFIGURATION		5
#define INCORRECT_NUMBER_OF_PLUGBOARD_PARAMETERS	6
#define INVALID_ROTOR_MAPPING				7
#define NO_ROTOR_STARTING_POSITION			8
#define INVALID_REFLECTOR_MAPPING			9
#define INCORRECT_NUMBER_OF_REFLECTOR_PARAMETERS	10
#define ERROR_OPENING_CONFIGURATION_FILE		11
#define NON_NUMERIC_CHARACTER_PLUGBOARD		12
#define NON_NUMERIC_CHARACTER_REFLECTOR		13
#define NON_NUMERIC_CHARACTER_ROTOR		14
#define NON_NUMERIC_CHARACTER_POSITIONS		15
#define INCORRECT_NUMBER_OF_REFLECTOR_PARAMETERS_ODD		16
#define INVALID_ROTOR_MAPPING_NOT_ENOUGH_PARAMETERS		17

#define NO_ERROR					0
